"use client";
import { useEffect, useMemo, useRef, useState, useCallback } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { PdfPages, type PageDims } from "@/components/PdfPages";
import { colorForRole } from "@/lib/role-color";
import { TemplateChatPanel } from "./TemplateChatPanel";

type FieldType = "text" | "signature" | "date" | "checkbox";

interface Field {
  id: string;
  type: FieldType;
  pageIndex: number;
  x: number;
  y: number;
  w: number;
  h: number;
  required: boolean;
  submitterRole: string;
  label?: string;
}

interface Role {
  name: string;
  order: number;
}

interface Template {
  id: string;
  name: string;
  fields: Field[];
  documents: {
    attachmentId: string;
    filename: string;
    pageCount: number;
    /** Present when the document was generated by AI — enables "Edit document" mode. */
    bodyMarkdown?: string;
  }[];
  submitterRoles: Role[];
  updatedAt: string;
}

const DEFAULT_W: Record<FieldType, number> = {
  text: 0.18,
  signature: 0.22,
  date: 0.12,
  checkbox: 0.025,
};
const DEFAULT_H: Record<FieldType, number> = {
  text: 0.025,
  signature: 0.05,
  date: 0.025,
  checkbox: 0.025,
};

function uuid() {
  return crypto.randomUUID();
}

/** Pragmatic email check — mirrors what the server's zod `.email()` accepts
 * closely enough to catch typos before the request is sent. */
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

/** Minimum field size in normalized units, so a box can't be shrunk to nothing. */
const MIN_W = 0.02;
const MIN_H = 0.012;

/** Resize handles drawn on the selected field. `cx`/`cy` are the handle's
 * fractional position within the box; `dir` names the edges it drags. */
const RESIZE_HANDLES: { dir: string; cx: number; cy: number; cursor: string }[] = [
  { dir: "nw", cx: 0, cy: 0, cursor: "nwse-resize" },
  { dir: "n", cx: 0.5, cy: 0, cursor: "ns-resize" },
  { dir: "ne", cx: 1, cy: 0, cursor: "nesw-resize" },
  { dir: "e", cx: 1, cy: 0.5, cursor: "ew-resize" },
  { dir: "se", cx: 1, cy: 1, cursor: "nwse-resize" },
  { dir: "s", cx: 0.5, cy: 1, cursor: "ns-resize" },
  { dir: "sw", cx: 0, cy: 1, cursor: "nesw-resize" },
  { dir: "w", cx: 0, cy: 0.5, cursor: "ew-resize" },
];

/**
 * Compute a new normalized box when dragging a resize handle. The edges named
 * in `dir` move with the pointer; opposite edges stay put. Enforces a minimum
 * size and clamps within the page [0,1].
 */
function resizeBox(
  dir: string,
  startX: number,
  startY: number,
  startW: number,
  startH: number,
  dx: number,
  dy: number,
): { x: number; y: number; w: number; h: number } {
  let x = startX;
  let y = startY;
  let w = startW;
  let h = startH;

  if (dir.includes("e")) w = startW + dx;
  if (dir.includes("s")) h = startH + dy;
  if (dir.includes("w")) {
    x = startX + dx;
    w = startW - dx;
  }
  if (dir.includes("n")) {
    y = startY + dy;
    h = startH - dy;
  }

  // Keep the dragged edge from crossing the opposite one.
  if (dir.includes("w") && w < MIN_W) {
    x = startX + startW - MIN_W;
    w = MIN_W;
  }
  if (dir.includes("n") && h < MIN_H) {
    y = startY + startH - MIN_H;
    h = MIN_H;
  }
  w = Math.max(MIN_W, w);
  h = Math.max(MIN_H, h);

  // Clamp to page bounds without flipping.
  if (x < 0) {
    w += x;
    x = 0;
  }
  if (y < 0) {
    h += y;
    y = 0;
  }
  if (x + w > 1) w = 1 - x;
  if (y + h > 1) h = 1 - y;

  return { x, y, w: Math.max(MIN_W, w), h: Math.max(MIN_H, h) };
}

/** Single source of truth for the role list — combines explicit roles
 * with anything referenced by a field, so AI-detected roles appear too. */
function deriveRoles(template: Template): Role[] {
  const explicit = template.submitterRoles ?? [];
  const fromFields = template.fields.map((f) => f.submitterRole);
  const seen = new Set<string>();
  const out: Role[] = [];
  for (const r of explicit) {
    if (r.name && !seen.has(r.name)) {
      seen.add(r.name);
      out.push(r);
    }
  }
  for (const name of fromFields) {
    if (name && !seen.has(name)) {
      seen.add(name);
      out.push({ name, order: out.length });
    }
  }
  if (out.length === 0) out.push({ name: "Signer", order: 0 });
  return out;
}

export function TemplateBuilder({ templateId }: { templateId: string }) {
  const router = useRouter();
  const [template, setTemplate] = useState<Template | null>(null);
  const [pdfUrl, setPdfUrl] = useState<string | null>(null);
  // null = no field-placement armed. The user must explicitly pick a type
  // before a click on the document adds a field, so stray clicks don't.
  const [activeTool, setActiveTool] = useState<FieldType | null>(null);
  const [activeRole, setActiveRole] = useState("Signer");
  const [saving, setSaving] = useState(false);
  const [showSendDialog, setShowSendDialog] = useState(false);
  const [detecting, setDetecting] = useState(false);
  const [detectError, setDetectError] = useState<string | null>(null);
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [clipboard, setClipboard] = useState<Field[]>([]);
  const [showDocumentEditor, setShowDocumentEditor] = useState(false);
  const [regenerating, setRegenerating] = useState(false);
  const [showChatPanel, setShowChatPanel] = useState(false);
  const [editingName, setEditingName] = useState(false);
  const [nameValue, setNameValue] = useState("");
  const nameInputRef = useRef<HTMLInputElement>(null);

  /** Drag state — populated on pointerdown over a field, cleared on pointerup.
   * "move" drags the body (possibly a group); "resize" drags one field's
   * handle (`handle` names the edge/corner, e.g. "se", "e", "n"). */
  const dragRef = useRef<{
    pointerId: number;
    mode: "move" | "resize";
    dims: PageDims;
    moved: boolean;
    startClientX: number;
    startClientY: number;
    // move: start positions of every field in the drag group
    starts?: { id: string; x: number; y: number }[];
    // resize: the single field being resized
    resizeId?: string;
    handle?: string;
    startX?: number;
    startY?: number;
    startW?: number;
    startH?: number;
  } | null>(null);

  /** The single selected field (for the inspector); null when 0 or >1 selected. */
  const selectedField = useMemo(
    () =>
      selectedIds.length === 1
        ? (template?.fields.find((f) => f.id === selectedIds[0]) ?? null)
        : null,
    [template?.fields, selectedIds],
  );

  const roles = useMemo(() => (template ? deriveRoles(template) : []), [template]);
  const fieldsByRole = useMemo(() => {
    const m = new Map<string, number>();
    for (const f of template?.fields ?? []) m.set(f.submitterRole, (m.get(f.submitterRole) ?? 0) + 1);
    return m;
  }, [template?.fields]);

  /** Total page count across the template's documents (fields use a global
   * 0-based page index). At least 1 so the control is well-formed. */
  const pageCount = useMemo(
    () => Math.max(1, (template?.documents ?? []).reduce((n, d) => n + (d.pageCount || 0), 0)),
    [template?.documents],
  );

  /** The page shared by all selected fields, or null when they span pages. */
  const selectedPage = useMemo(() => {
    const pages = new Set(
      (template?.fields ?? []).filter((f) => selectedIds.includes(f.id)).map((f) => f.pageIndex),
    );
    return pages.size === 1 ? [...pages][0]! : null;
  }, [template?.fields, selectedIds]);

  // Keep activeRole valid as roles change (AI detect may add new ones).
  useEffect(() => {
    if (roles.length === 0) return;
    if (!roles.find((r) => r.name === activeRole)) setActiveRole(roles[0]!.name);
  }, [roles, activeRole]);

  // Load template — when arriving from the AI-generation flow, poll until the
  // worker finishes filling in documents+fields.
  useEffect(() => {
    let cancelled = false;
    const params = new URLSearchParams(window.location.search);
    const awaitDraft = params.get("await_draft") === "1";
    const deadline = Date.now() + 90_000;

    async function tick() {
      const res = await fetch(`/api/templates/${templateId}`);
      if (!res.ok) return;
      const { template: latest } = (await res.json()) as { template: Template };
      if (cancelled) return;
      setTemplate(latest);
      if (awaitDraft && latest.documents.length === 0 && Date.now() < deadline) {
        setTimeout(tick, 2000);
      } else if (awaitDraft) {
        const url = new URL(window.location.href);
        url.searchParams.delete("await_draft");
        window.history.replaceState({}, "", url.toString());
      }
    }
    tick();
    return () => {
      cancelled = true;
    };
  }, [templateId]);

  // Resolve the streaming URL for the first document.
  useEffect(() => {
    const docId = template?.documents[0]?.attachmentId;
    if (!docId) return;
    fetch(`/api/attachments/${docId}`)
      .then((r) => r.json())
      .then((d: { url: string }) => setPdfUrl(d.url));
  }, [template?.documents]);

  const placeField = useCallback(
    (pageIndex: number, normalized: { x: number; y: number }) => {
      // Only place when a field type has been explicitly armed. A click on an
      // empty part of the document otherwise just clears the selection.
      if (!activeTool) {
        setSelectedIds([]);
        return;
      }
      const tool = activeTool;
      const newId = uuid();
      setTemplate((prev) => {
        if (!prev) return prev;
        const w = DEFAULT_W[tool];
        const h = DEFAULT_H[tool];
        const next: Field = {
          id: newId,
          type: tool,
          pageIndex,
          x: Math.max(0, Math.min(1 - w, normalized.x - w / 2)),
          y: Math.max(0, Math.min(1 - h, normalized.y - h / 2)),
          w,
          h,
          required: true,
          submitterRole: activeRole,
        };
        return { ...prev, fields: [...prev.fields, next] };
      });
      // Disarm after placing one field, and select it for immediate tweaking.
      setActiveTool(null);
      setSelectedIds([newId]);
    },
    [activeTool, activeRole],
  );

  const removeField = useCallback((id: string) => {
    setTemplate((prev) =>
      prev ? { ...prev, fields: prev.fields.filter((f) => f.id !== id) } : prev,
    );
    setSelectedIds((cur) => cur.filter((i) => i !== id));
  }, []);

  const removeSelected = useCallback(() => {
    setTemplate((prev) =>
      prev ? { ...prev, fields: prev.fields.filter((f) => !selectedIds.includes(f.id)) } : prev,
    );
    setSelectedIds([]);
  }, [selectedIds]);

  /** Move every selected field to another page, keeping their x/y positions. */
  const moveSelectedToPage = useCallback(
    (pageIndex: number) => {
      setTemplate((prev) =>
        prev
          ? {
              ...prev,
              fields: prev.fields.map((f) =>
                selectedIds.includes(f.id) ? { ...f, pageIndex } : f,
              ),
            }
          : prev,
      );
    },
    [selectedIds],
  );

  const updateField = useCallback((id: string, patch: Partial<Field>) => {
    setTemplate((prev) =>
      prev
        ? { ...prev, fields: prev.fields.map((f) => (f.id === id ? { ...f, ...patch } : f)) }
        : prev,
    );
  }, []);

  /** Copy the current selection to the in-editor clipboard. */
  const copySelected = useCallback(() => {
    const sel = template?.fields.filter((f) => selectedIds.includes(f.id)) ?? [];
    if (sel.length) setClipboard(sel.map((f) => ({ ...f })));
  }, [template?.fields, selectedIds]);

  /** Paste clipboard fields, offset slightly, reassigned to the ACTIVE signer
   * (so you can paste a group "under another signer color" by selecting that
   * signer first). New ids; the pasted fields become the selection. */
  const pasteClipboard = useCallback(() => {
    if (clipboard.length === 0) return;
    const OFFSET = 0.02;
    const pasted: Field[] = clipboard.map((f) => ({
      ...f,
      id: uuid(),
      x: Math.max(0, Math.min(1 - f.w, f.x + OFFSET)),
      y: Math.max(0, Math.min(1 - f.h, f.y + OFFSET)),
      submitterRole: activeRole,
    }));
    setTemplate((prev) => (prev ? { ...prev, fields: [...prev.fields, ...pasted] } : prev));
    setSelectedIds(pasted.map((f) => f.id));
  }, [clipboard, activeRole]);

  // Keyboard shortcuts: Esc clears selection/placement, Cmd/Ctrl+C/V copy &
  // paste the selection, Delete/Backspace removes it. Ignored while typing.
  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      const el = e.target as HTMLElement | null;
      const typing =
        el?.tagName === "INPUT" || el?.tagName === "TEXTAREA" || el?.isContentEditable === true;
      if (e.key === "Escape") {
        setSelectedIds([]);
        setActiveTool(null);
        return;
      }
      if (typing) return;
      const meta = e.metaKey || e.ctrlKey;
      if (meta && e.key.toLowerCase() === "c" && selectedIds.length) {
        e.preventDefault();
        copySelected();
      } else if (meta && e.key.toLowerCase() === "v" && clipboard.length) {
        e.preventDefault();
        pasteClipboard();
      } else if ((e.key === "Delete" || e.key === "Backspace") && selectedIds.length) {
        e.preventDefault();
        removeSelected();
      }
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [selectedIds, clipboard, copySelected, pasteClipboard, removeSelected]);

  // ----- Drag handlers (selection + move on the same pointer gesture) -----

  const onFieldPointerDown = useCallback(
    (e: React.PointerEvent<HTMLDivElement>, field: Field, dims: PageDims) => {
      e.stopPropagation();
      const additive = e.shiftKey || e.metaKey || e.ctrlKey;

      // Shift/Cmd-click toggles the field in the selection without dragging.
      if (additive) {
        setSelectedIds((cur) =>
          cur.includes(field.id) ? cur.filter((i) => i !== field.id) : [...cur, field.id],
        );
        return;
      }

      // Plain click: if the field is part of an existing multi-selection, drag
      // the whole group; otherwise select just this one and drag it.
      const groupIds =
        selectedIds.includes(field.id) && selectedIds.length > 1 ? selectedIds : [field.id];
      if (groupIds.length === 1) setSelectedIds([field.id]);

      e.currentTarget.setPointerCapture(e.pointerId);
      const starts = (template?.fields ?? [])
        .filter((f) => groupIds.includes(f.id))
        .map((f) => ({ id: f.id, x: f.x, y: f.y }));
      dragRef.current = {
        pointerId: e.pointerId,
        mode: "move",
        dims,
        moved: false,
        startClientX: e.clientX,
        startClientY: e.clientY,
        starts,
      };
    },
    [selectedIds, template?.fields],
  );

  const onHandlePointerDown = useCallback(
    (e: React.PointerEvent<HTMLDivElement>, field: Field, dims: PageDims, handle: string) => {
      e.stopPropagation();
      e.currentTarget.setPointerCapture(e.pointerId);
      setSelectedIds([field.id]);
      dragRef.current = {
        pointerId: e.pointerId,
        mode: "resize",
        dims,
        moved: false,
        startClientX: e.clientX,
        startClientY: e.clientY,
        resizeId: field.id,
        handle,
        startX: field.x,
        startY: field.y,
        startW: field.w,
        startH: field.h,
      };
    },
    [],
  );

  const onFieldPointerMove = useCallback((e: React.PointerEvent<HTMLDivElement>) => {
    const s = dragRef.current;
    if (!s || s.pointerId !== e.pointerId) return;
    const pxDx = e.clientX - s.startClientX;
    const pxDy = e.clientY - s.startClientY;
    if (!s.moved && (Math.abs(pxDx) > 3 || Math.abs(pxDy) > 3)) {
      s.moved = true;
    }
    if (!s.moved) return;
    const dx = pxDx / s.dims.widthPx;
    const dy = pxDy / s.dims.heightPx;

    if (s.mode === "resize") {
      const box = resizeBox(s.handle!, s.startX!, s.startY!, s.startW!, s.startH!, dx, dy);
      setTemplate((prev) =>
        prev
          ? {
              ...prev,
              fields: prev.fields.map((f) => (f.id === s.resizeId ? { ...f, ...box } : f)),
            }
          : prev,
      );
      return;
    }

    // Move: shift every field in the drag group by the same delta.
    const startMap = new Map((s.starts ?? []).map((p) => [p.id, p]));
    setTemplate((prev) => {
      if (!prev) return prev;
      return {
        ...prev,
        fields: prev.fields.map((f) => {
          const st = startMap.get(f.id);
          if (!st) return f;
          return {
            ...f,
            x: Math.max(0, Math.min(1 - f.w, st.x + dx)),
            y: Math.max(0, Math.min(1 - f.h, st.y + dy)),
          };
        }),
      };
    });
  }, []);

  const onFieldPointerUp = useCallback((e: React.PointerEvent<HTMLDivElement>) => {
    const s = dragRef.current;
    if (!s || s.pointerId !== e.pointerId) return;
    try {
      e.currentTarget.releasePointerCapture(e.pointerId);
    } catch {
      // ignore — capture may already be released
    }
    dragRef.current = null;
  }, []);

  function addRole(name: string) {
    const trimmed = name.trim();
    if (!trimmed) return;
    setTemplate((prev) => {
      if (!prev) return prev;
      if (prev.submitterRoles.some((r) => r.name === trimmed)) return prev;
      return {
        ...prev,
        submitterRoles: [...prev.submitterRoles, { name: trimmed, order: prev.submitterRoles.length }],
      };
    });
    setActiveRole(trimmed);
  }

  function removeRole(name: string) {
    if (fieldsByRole.has(name)) {
      if (
        !confirm(
          `"${name}" has ${fieldsByRole.get(name)} field(s). Remove role and ALL its fields?`,
        )
      ) {
        return;
      }
    }
    setTemplate((prev) => {
      if (!prev) return prev;
      return {
        ...prev,
        submitterRoles: prev.submitterRoles.filter((r) => r.name !== name),
        fields: prev.fields.filter((f) => f.submitterRole !== name),
      };
    });
  }

  async function save() {
    if (!template) return;
    setSaving(true);
    try {
      await fetch(`/api/templates/${templateId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          fields: template.fields,
          submitterRoles: template.submitterRoles,
        }),
      });
    } finally {
      setSaving(false);
    }
  }

  function startEditName() {
    if (!template) return;
    setNameValue(template.name);
    setEditingName(true);
    setTimeout(() => nameInputRef.current?.select(), 0);
  }

  async function commitName() {
    const name = nameValue.trim();
    if (!name || !template) { setEditingName(false); return; }
    if (name === template.name) { setEditingName(false); return; }
    await fetch(`/api/templates/${templateId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name }),
    });
    setTemplate((prev) => prev ? { ...prev, name } : prev);
    setEditingName(false);
  }

  async function regenerateFromMarkdown(bodyMarkdown: string, title?: string) {
    setRegenerating(true);
    try {
      const res = await fetch(`/api/templates/${templateId}/regenerate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ bodyMarkdown, title }),
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body?.error ?? `HTTP ${res.status}`);
      }
      const { template: updated } = (await res.json()) as { template: Template };
      setTemplate(updated);
      setShowDocumentEditor(false);
      // Force the PDF preview to refetch with the new attachment.
      setPdfUrl(null);
    } finally {
      setRegenerating(false);
    }
  }

  async function autoDetect() {
    setDetecting(true);
    setDetectError(null);
    try {
      const enqueue = await fetch(`/api/templates/${templateId}/detect-fields`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        // Replace so re-running gives a clean, correctly-positioned set rather
        // than stacking another copy on top of the previous detection.
        body: JSON.stringify({ replace: true }),
      });
      if (!enqueue.ok) {
        const body = await enqueue.json().catch(() => ({}));
        throw new Error(body?.error ?? `HTTP ${enqueue.status}`);
      }
      // Poll on updatedAt rather than field count — with replace the count can
      // stay the same even though positions changed.
      const before = template?.updatedAt;
      const deadline = Date.now() + 90_000;
      while (Date.now() < deadline) {
        await new Promise((r) => setTimeout(r, 2000));
        const res = await fetch(`/api/templates/${templateId}`);
        if (!res.ok) continue;
        const { template: latest } = (await res.json()) as { template: Template };
        if (latest.updatedAt !== before) {
          setTemplate(latest);
          return;
        }
      }
      setDetectError("Detection timed out. Check worker logs.");
    } catch (err) {
      const msg = err instanceof Error ? err.message : "detect_failed";
      setDetectError(msg);
    } finally {
      setDetecting(false);
    }
  }

  if (!template) return <p className="p-8 text-zinc-500">Loading…</p>;

  return (
    <div className="flex flex-col h-screen bg-white dark:bg-zinc-950">
      <header className="shrink-0 border-b border-zinc-200 dark:border-zinc-800 bg-white/80 dark:bg-zinc-950/80 backdrop-blur px-6 py-2.5 flex items-center justify-between gap-4">
        <nav className="flex items-center gap-2 text-sm text-zinc-500 min-w-0">
          <Link href="/dashboard" className="hover:text-zinc-900 dark:hover:text-zinc-100">
            Dashboard
          </Link>
          <span className="text-zinc-300 dark:text-zinc-700">/</span>
          <Link href="/templates" className="hover:text-zinc-900 dark:hover:text-zinc-100">
            Templates
          </Link>
        </nav>
        {editingName ? (
          <form
            className="flex-1 min-w-0 flex items-center justify-center gap-1"
            onSubmit={(e) => { e.preventDefault(); commitName(); }}
          >
            <input
              ref={nameInputRef}
              value={nameValue}
              onChange={(e) => setNameValue(e.target.value)}
              onKeyDown={(e) => e.key === "Escape" && setEditingName(false)}
              onBlur={commitName}
              className="w-64 px-2 py-0.5 text-sm font-semibold text-center rounded border border-emerald-400 focus:outline-none focus:ring-1 focus:ring-emerald-500 bg-white dark:bg-zinc-900"
            />
          </form>
        ) : (
          <button
            type="button"
            onClick={startEditName}
            title="Click to rename"
            className="font-semibold truncate flex-1 min-w-0 text-center hover:text-emerald-700 dark:hover:text-emerald-400 transition-colors"
          >
            {template.name}
          </button>
        )}
        <div className="flex items-center gap-2 shrink-0">
          {template.documents[0]?.bodyMarkdown !== undefined && (
            <button
              type="button"
              onClick={() => setShowDocumentEditor(true)}
              title="Edit the AI-generated document body and re-render the PDF"
              className="px-3 py-1.5 text-sm border border-zinc-300 dark:border-zinc-700 rounded-md hover:bg-zinc-50 dark:hover:bg-zinc-800"
            >
              Edit document
            </button>
          )}
          <button
            type="button"
            onClick={() => setShowChatPanel((v) => !v)}
            title="Open AI assistant"
            className={`px-3 py-1.5 text-sm rounded-md border transition-colors ${
              showChatPanel
                ? "bg-emerald-50 border-emerald-300 text-emerald-800 dark:bg-emerald-950 dark:border-emerald-700 dark:text-emerald-200"
                : "border-zinc-300 dark:border-zinc-700 hover:bg-zinc-50 dark:hover:bg-zinc-800"
            }`}
          >
            ✨ AI Assistant
          </button>
          <button
            type="button"
            onClick={autoDetect}
            disabled={detecting}
            title="Use AI to detect signature, date, text and checkbox fields per signer"
            className="px-3 py-1.5 text-sm border border-emerald-300 text-emerald-700 dark:border-emerald-700 dark:text-emerald-300 rounded-md hover:bg-emerald-50 dark:hover:bg-emerald-950 transition-colors disabled:opacity-50"
          >
            {detecting ? "Detecting…" : "✨ Auto-detect fields"}
          </button>
          <button
            type="button"
            onClick={save}
            disabled={saving}
            className="px-3 py-1.5 text-sm border border-zinc-300 dark:border-zinc-700 rounded-md hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-colors disabled:opacity-50"
          >
            {saving ? "Saving…" : "Save"}
          </button>
          <button
            type="button"
            onClick={() => setShowSendDialog(true)}
            className="px-3 py-1.5 text-sm bg-emerald-500 text-white rounded-md font-medium shadow-sm hover:bg-emerald-400 transition-colors"
          >
            Send for signing
          </button>
        </div>
      </header>

      <div className="flex flex-1 min-h-0">
        <aside className="w-64 shrink-0 overflow-y-auto border-r border-zinc-200 dark:border-zinc-800 p-4 space-y-5">
          <div>
            <h3 className="text-xs uppercase tracking-wide text-zinc-500 mb-2">Add field</h3>
            <div className="space-y-1">
              {(["signature", "text", "date", "checkbox"] as FieldType[]).map((t) => (
                <button
                  key={t}
                  type="button"
                  onClick={() => setActiveTool((cur) => (cur === t ? null : t))}
                  aria-pressed={activeTool === t}
                  className={`block w-full text-left px-2.5 py-1.5 rounded-md text-sm capitalize border transition-colors ${
                    activeTool === t
                      ? "bg-emerald-50 text-emerald-800 border-emerald-300 dark:bg-emerald-950 dark:text-emerald-200 dark:border-emerald-800 font-medium"
                      : "border-transparent text-zinc-600 dark:text-zinc-300 hover:bg-zinc-100 dark:hover:bg-zinc-800"
                  }`}
                >
                  {t}
                </button>
              ))}
            </div>
            {activeTool ? (
              <div className="mt-2 flex items-center justify-between gap-2">
                <p className="text-xs text-emerald-700 dark:text-emerald-300">
                  Click on the document to place a {activeTool} field.
                </p>
                <button
                  type="button"
                  onClick={() => setActiveTool(null)}
                  className="text-xs text-zinc-500 hover:text-zinc-800 dark:hover:text-zinc-200 shrink-0"
                >
                  Cancel
                </button>
              </div>
            ) : (
              <p className="text-xs text-zinc-500 mt-2">
                Pick a field type, then click where it goes.
              </p>
            )}
          </div>

          <SignersPanel
            roles={roles}
            activeRole={activeRole}
            fieldsByRole={fieldsByRole}
            onSelect={setActiveRole}
            onAdd={addRole}
            onRemove={removeRole}
          />

          {detectError && (
            <div className="text-xs text-red-500 bg-red-50 dark:bg-red-950 px-2 py-1 rounded">
              {detectError}
            </div>
          )}

          {selectedField && (
            <FieldInspector
              field={selectedField}
              roles={roles}
              onChange={(patch) => updateField(selectedField.id, patch)}
              onDelete={() => removeField(selectedField.id)}
              onClose={() => setSelectedIds([])}
            />
          )}

          {selectedIds.length > 1 && (
            <div className="rounded-lg border border-emerald-200 dark:border-emerald-900 bg-emerald-50/50 dark:bg-emerald-950/30 p-3 space-y-2">
              <p className="text-sm font-medium">{selectedIds.length} fields selected</p>
              <div className="flex flex-wrap gap-2">
                <button
                  type="button"
                  onClick={copySelected}
                  className="px-2.5 py-1 text-xs rounded-md border border-zinc-300 dark:border-zinc-700 hover:bg-white dark:hover:bg-zinc-800"
                >
                  Copy
                </button>
                <button
                  type="button"
                  onClick={removeSelected}
                  className="px-2.5 py-1 text-xs rounded-md border border-red-300 text-red-600 hover:bg-red-50 dark:border-red-900 dark:hover:bg-red-950"
                >
                  Delete
                </button>
                <button
                  type="button"
                  onClick={() => setSelectedIds([])}
                  className="px-2.5 py-1 text-xs rounded-md text-zinc-500 hover:text-zinc-800 dark:hover:text-zinc-200"
                >
                  Clear
                </button>
              </div>
              <p className="text-xs text-zinc-500">
                Drag any selected field to move them together. ⌘/Ctrl+C, then pick a signer and
                ⌘/Ctrl+V to paste under that signer.
              </p>
            </div>
          )}

          {clipboard.length > 0 && (
            <button
              type="button"
              onClick={pasteClipboard}
              className="w-full px-2.5 py-1.5 text-xs rounded-md border border-dashed border-zinc-300 dark:border-zinc-700 text-zinc-600 dark:text-zinc-300 hover:bg-zinc-50 dark:hover:bg-zinc-800"
            >
              Paste {clipboard.length} field{clipboard.length > 1 ? "s" : ""} → {activeRole}
            </button>
          )}

          {selectedIds.length >= 1 && pageCount > 1 && (
            <div className="flex items-center justify-between gap-2 text-sm">
              <label htmlFor="move-to-page" className="text-xs text-zinc-500">
                Move {selectedIds.length > 1 ? `${selectedIds.length} fields` : "field"} to page
              </label>
              <select
                id="move-to-page"
                value={selectedPage ?? ""}
                onChange={(e) => moveSelectedToPage(Number(e.target.value))}
                className="rounded-md border border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-900 text-sm px-2 py-1"
              >
                {selectedPage === null && <option value="">—</option>}
                {Array.from({ length: pageCount }, (_, i) => (
                  <option key={i} value={i}>
                    {i + 1}
                  </option>
                ))}
              </select>
            </div>
          )}

          <div>
            <h3 className="text-xs uppercase tracking-wide text-zinc-500 mb-2 flex items-center gap-1.5">
              <span
                className="h-2 w-2 rounded-full shrink-0"
                style={{ backgroundColor: colorForRole(activeRole).border }}
              />
              {activeRole} fields ({fieldsByRole.get(activeRole) ?? 0})
            </h3>
            <ul className="text-xs space-y-1">
              {template.fields
                .filter((f) => f.submitterRole === activeRole)
                .map((f) => {
                  const c = colorForRole(f.submitterRole);
                  const isSelected = selectedIds.includes(f.id);
                  return (
                    <li
                      key={f.id}
                      className={`flex items-center justify-between gap-1 px-1.5 py-1 rounded cursor-pointer ${
                        isSelected
                          ? "bg-zinc-100 dark:bg-zinc-800 ring-1 ring-zinc-300 dark:ring-zinc-700"
                          : "hover:bg-zinc-50 dark:hover:bg-zinc-900"
                      }`}
                      onClick={(e) =>
                        setSelectedIds((cur) =>
                          e.shiftKey || e.metaKey || e.ctrlKey
                            ? cur.includes(f.id)
                              ? cur.filter((i) => i !== f.id)
                              : [...cur, f.id]
                            : [f.id],
                        )
                      }
                    >
                      <span className="flex items-center gap-1.5 truncate">
                        <span
                          className="h-2 w-2 rounded-full shrink-0"
                          style={{ backgroundColor: c.border }}
                        />
                        <span className="truncate">{f.label ?? f.type}</span>
                        <span className="text-zinc-400 shrink-0">· p{f.pageIndex + 1}</span>
                      </span>
                      <button
                        type="button"
                        onClick={(e) => {
                          e.stopPropagation();
                          removeField(f.id);
                        }}
                        className="text-zinc-400 hover:text-red-500"
                      >
                        ×
                      </button>
                    </li>
                  );
                })}
              {(fieldsByRole.get(activeRole) ?? 0) === 0 && (
                <li className="text-zinc-500 italic">
                  No fields for this signer yet — pick a field type above, then click the
                  document.
                </li>
              )}
            </ul>
          </div>
        </aside>

        <div className="flex-1 overflow-auto p-6 bg-zinc-50 dark:bg-zinc-900">
          {pdfUrl ? (
            <div className="mx-auto inline-block">
              <PdfPages
                url={pdfUrl}
                pageWidthPx={760}
                placing={activeTool !== null}
                onPageClick={placeField}
                overlay={(pageIndex, dims) => (
                  <>
                    {template.fields
                      .filter((f) => f.pageIndex === pageIndex)
                      .map((f) => {
                        const c = colorForRole(f.submitterRole);
                        const isActiveRole = f.submitterRole === activeRole;
                        const isSelected = selectedIds.includes(f.id);
                        const labelText = f.label ?? f.type;
                        return (
                          <div
                            key={f.id}
                            className="absolute rounded-sm flex items-center justify-center font-medium text-[10px] select-none"
                            style={{
                              left: f.x * dims.widthPx,
                              top: f.y * dims.heightPx,
                              width: f.w * dims.widthPx,
                              height: f.h * dims.heightPx,
                              border: `${isSelected ? 2 : 2}px solid ${c.border}`,
                              outline: isSelected ? `2px solid ${c.border}` : "none",
                              outlineOffset: isSelected ? 2 : 0,
                              backgroundColor: c.fill,
                              color: c.text,
                              opacity: isActiveRole || isSelected ? 1 : 0.55,
                              cursor: dragRef.current?.mode === "move" && isSelected ? "grabbing" : "grab",
                              pointerEvents: "auto",
                              touchAction: "none",
                              padding: "0 4px",
                              // Visible so edge handles aren't clipped; the label
                              // itself truncates via the inner span below.
                              overflow: "visible",
                            }}
                            onPointerDown={(e) => onFieldPointerDown(e, f, dims)}
                            onPointerMove={onFieldPointerMove}
                            onPointerUp={onFieldPointerUp}
                            onPointerCancel={onFieldPointerUp}
                            onClick={(e) => e.stopPropagation()}
                            title={`${labelText} · ${f.submitterRole}`}
                          >
                            <span className="overflow-hidden text-ellipsis whitespace-nowrap max-w-full">
                              {labelText}
                            </span>
                            {isSelected &&
                              selectedIds.length === 1 &&
                              RESIZE_HANDLES.map((hd) => (
                                <div
                                  key={hd.dir}
                                  onPointerDown={(e) => onHandlePointerDown(e, f, dims, hd.dir)}
                                  onPointerMove={onFieldPointerMove}
                                  onPointerUp={onFieldPointerUp}
                                  onPointerCancel={onFieldPointerUp}
                                  onClick={(e) => e.stopPropagation()}
                                  className="absolute h-2 w-2 rounded-[1px] bg-white"
                                  style={{
                                    left: `${hd.cx * 100}%`,
                                    top: `${hd.cy * 100}%`,
                                    transform: "translate(-50%, -50%)",
                                    border: `1px solid ${c.border}`,
                                    cursor: hd.cursor,
                                    touchAction: "none",
                                  }}
                                />
                              ))}
                          </div>
                        );
                      })}
                  </>
                )}
              />
            </div>
          ) : (
            <div className="flex h-full items-center justify-center">
              <div className="flex flex-col items-center gap-3 text-zinc-500">
                <span className="h-6 w-6 rounded-full border-2 border-zinc-300 border-t-emerald-500 animate-spin dark:border-zinc-700 dark:border-t-emerald-400" />
                <p className="text-sm">Loading PDF…</p>
              </div>
            </div>
          )}
        </div>

        {showChatPanel && (
          <TemplateChatPanel
            templateId={templateId}
            bodyMarkdown={template.documents[0]?.bodyMarkdown}
            onClose={() => setShowChatPanel(false)}
            onApplyEdit={
              template.documents[0]?.bodyMarkdown !== undefined
                ? async (markdown) => { await regenerateFromMarkdown(markdown); }
                : undefined
            }
            applying={regenerating}
          />
        )}
      </div>

      {showSendDialog && (
        <SendDialog
          template={template}
          roles={roles}
          onClose={() => setShowSendDialog(false)}
          onSent={(submissionId) => router.push(`/submissions/${submissionId}`)}
        />
      )}

      {showDocumentEditor && template.documents[0]?.bodyMarkdown !== undefined && (
        <DocumentEditor
          initialBody={template.documents[0].bodyMarkdown}
          initialTitle={template.name}
          busy={regenerating}
          onClose={() => setShowDocumentEditor(false)}
          onSave={(body, title) => regenerateFromMarkdown(body, title)}
        />
      )}
    </div>
  );
}

function SignersPanel({
  roles,
  activeRole,
  fieldsByRole,
  onSelect,
  onAdd,
  onRemove,
}: {
  roles: Role[];
  activeRole: string;
  fieldsByRole: Map<string, number>;
  onSelect: (name: string) => void;
  onAdd: (name: string) => void;
  onRemove: (name: string) => void;
}) {
  const [newRole, setNewRole] = useState("");

  function handleAdd(e: React.FormEvent) {
    e.preventDefault();
    if (!newRole.trim()) return;
    onAdd(newRole);
    setNewRole("");
  }

  return (
    <div>
      <h3 className="text-xs uppercase tracking-wide text-zinc-500 mb-2">
        Signers ({roles.length})
      </h3>
      <ul className="space-y-1">
        {roles.map((r) => {
          const c = colorForRole(r.name);
          const isActive = r.name === activeRole;
          const count = fieldsByRole.get(r.name) ?? 0;
          return (
            <li
              key={r.name}
              className={`group flex items-center justify-between gap-2 px-2 py-1.5 rounded text-sm cursor-pointer ${
                isActive
                  ? "bg-zinc-100 dark:bg-zinc-800 ring-1"
                  : "hover:bg-zinc-50 dark:hover:bg-zinc-900"
              }`}
              style={isActive ? { boxShadow: `inset 0 0 0 1px ${c.border}` } : undefined}
              onClick={() => onSelect(r.name)}
            >
              <span className="flex items-center gap-2 min-w-0">
                <span
                  className="h-2.5 w-2.5 rounded-full shrink-0"
                  style={{ backgroundColor: c.border }}
                />
                <span className="truncate" style={isActive ? { color: c.text } : undefined}>
                  {r.name}
                </span>
                <span className="text-xs text-zinc-400">{count}</span>
              </span>
              <button
                type="button"
                onClick={(e) => {
                  e.stopPropagation();
                  onRemove(r.name);
                }}
                className="text-zinc-400 hover:text-red-500 opacity-0 group-hover:opacity-100"
                title="Remove signer"
              >
                ×
              </button>
            </li>
          );
        })}
      </ul>
      <form onSubmit={handleAdd} className="mt-2 flex gap-1">
        <input
          type="text"
          value={newRole}
          onChange={(e) => setNewRole(e.target.value)}
          placeholder="Add signer (e.g. Tenant)"
          className="flex-1 px-2 py-1 text-xs rounded-md border border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-900"
        />
        <button
          type="submit"
          disabled={!newRole.trim()}
          className="px-2 py-1 text-xs bg-zinc-900 dark:bg-zinc-100 text-white dark:text-zinc-900 rounded-md disabled:opacity-30"
        >
          +
        </button>
      </form>
      <p className="text-xs text-zinc-500 mt-1.5">
        Selected signer's color is used for new fields you place.
      </p>
    </div>
  );
}

function FieldInspector({
  field,
  roles,
  onChange,
  onDelete,
  onClose,
}: {
  field: Field;
  roles: Role[];
  onChange: (patch: Partial<Field>) => void;
  onDelete: () => void;
  onClose: () => void;
}) {
  const c = colorForRole(field.submitterRole);
  return (
    <div
      className="rounded-md border p-3 space-y-2"
      style={{ borderColor: c.border, backgroundColor: c.fill }}
    >
      <div className="flex items-center justify-between">
        <h3 className="text-xs uppercase tracking-wide font-semibold" style={{ color: c.text }}>
          {field.type} field
        </h3>
        <button
          type="button"
          onClick={onClose}
          className="text-zinc-400 hover:text-zinc-700 dark:hover:text-zinc-200"
          title="Close (Esc)"
        >
          ×
        </button>
      </div>

      <label className="block">
        <span className="text-[10px] uppercase tracking-wide text-zinc-500">Name</span>
        <input
          type="text"
          value={field.label ?? ""}
          onChange={(e) => onChange({ label: e.target.value || undefined })}
          placeholder={field.type}
          className="mt-0.5 w-full px-2 py-1 text-sm rounded-md border border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-900"
        />
      </label>

      <label className="block">
        <span className="text-[10px] uppercase tracking-wide text-zinc-500">Signer</span>
        <select
          value={field.submitterRole}
          onChange={(e) => onChange({ submitterRole: e.target.value })}
          className="mt-0.5 w-full px-2 py-1 text-sm rounded-md border border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-900"
        >
          {roles.map((r) => (
            <option key={r.name} value={r.name}>
              {r.name}
            </option>
          ))}
        </select>
      </label>

      <label className="flex items-center gap-2 text-sm">
        <input
          type="checkbox"
          checked={field.required}
          onChange={(e) => onChange({ required: e.target.checked })}
        />
        Required
      </label>

      <div className="text-[10px] text-zinc-500">
        page {field.pageIndex + 1} · {(field.x * 100).toFixed(1)}%, {(field.y * 100).toFixed(1)}%
      </div>

      <button
        type="button"
        onClick={onDelete}
        className="w-full px-2 py-1 text-xs text-red-600 dark:text-red-400 border border-red-200 dark:border-red-900 rounded-md hover:bg-red-50 dark:hover:bg-red-950"
      >
        Delete field
      </button>
    </div>
  );
}

function DocumentEditor({
  initialBody,
  initialTitle,
  busy,
  onClose,
  onSave,
}: {
  initialBody: string;
  initialTitle: string;
  busy: boolean;
  onClose: () => void;
  onSave: (body: string, title: string) => void;
}) {
  const [title, setTitle] = useState(initialTitle);
  const [body, setBody] = useState(initialBody);

  return (
    <div className="fixed inset-0 bg-black/40 flex items-center justify-center p-4 z-50">
      <div className="bg-white dark:bg-zinc-900 rounded-lg shadow-xl w-full max-w-3xl max-h-[90vh] flex flex-col overflow-hidden">
        <div className="px-5 py-3 border-b border-zinc-200 dark:border-zinc-800 flex items-center justify-between">
          <h2 className="text-lg font-semibold">Edit document</h2>
          <button
            type="button"
            onClick={onClose}
            className="text-zinc-400 hover:text-zinc-700 dark:hover:text-zinc-200"
          >
            ×
          </button>
        </div>
        <div className="px-5 py-4 space-y-3 overflow-y-auto">
          <div>
            <label className="text-[10px] uppercase tracking-wide text-zinc-500 block">Title</label>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="mt-0.5 w-full px-3 py-2 text-sm rounded-md border border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-900"
            />
          </div>
          <div>
            <label className="text-[10px] uppercase tracking-wide text-zinc-500 block">
              Body (markdown)
            </label>
            <textarea
              rows={22}
              value={body}
              onChange={(e) => setBody(e.target.value)}
              className="mt-0.5 w-full px-3 py-2 text-sm font-mono rounded-md border border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-900 leading-relaxed"
            />
            <div className="mt-2 rounded-md border border-zinc-200 dark:border-zinc-700 divide-y divide-zinc-200 dark:divide-zinc-700 text-[11px] text-zinc-500 leading-relaxed">
              <div className="px-3 py-2 space-y-1">
                <p className="font-medium text-zinc-600 dark:text-zinc-400">Field placeholders</p>
                <p>
                  <code className="bg-zinc-100 dark:bg-zinc-800 px-1 rounded">[SIGNATURE: Role]</code>{" "}
                  <code className="bg-zinc-100 dark:bg-zinc-800 px-1 rounded">[DATE: Role]</code>{" "}
                  <code className="bg-zinc-100 dark:bg-zinc-800 px-1 rounded">[TEXT: &quot;Label&quot;, Role]</code>{" "}
                  <code className="bg-zinc-100 dark:bg-zinc-800 px-1 rounded">[CHECKBOX: &quot;Label&quot;, Role]</code>
                </p>
                <p>Put each placeholder on its own line. Saving rebuilds the PDF — drag-placed fields will be lost.</p>
              </div>
              <div className="px-3 py-2 space-y-1">
                <p className="font-medium text-zinc-600 dark:text-zinc-400">Tables</p>
                <pre className="bg-zinc-100 dark:bg-zinc-800 rounded px-2 py-1.5 text-[10px] leading-snug overflow-x-auto whitespace-pre">
{`| Column A | Column B | Column C |
|----------|----------|----------|
| Value 1  | Value 2  | Value 3  |`}
                </pre>
                <p>Tables render with a dark header row and alternating row shading.</p>
              </div>
              <div className="px-3 py-2 space-y-0.5">
                <p className="font-medium text-zinc-600 dark:text-zinc-400">Other formatting</p>
                <p>
                  <code className="bg-zinc-100 dark:bg-zinc-800 px-1 rounded"># H1</code>{" "}
                  <code className="bg-zinc-100 dark:bg-zinc-800 px-1 rounded">## H2</code>{" "}
                  <code className="bg-zinc-100 dark:bg-zinc-800 px-1 rounded">**bold**</code>{" "}
                  <code className="bg-zinc-100 dark:bg-zinc-800 px-1 rounded">*italic*</code>{" "}
                  <code className="bg-zinc-100 dark:bg-zinc-800 px-1 rounded">- bullet</code>{" "}
                  <code className="bg-zinc-100 dark:bg-zinc-800 px-1 rounded">1. numbered</code>{" "}
                  <code className="bg-zinc-100 dark:bg-zinc-800 px-1 rounded">&gt; blockquote</code>{" "}
                  <code className="bg-zinc-100 dark:bg-zinc-800 px-1 rounded">---</code>
                </p>
              </div>
            </div>
          </div>
        </div>
        <div className="px-5 py-3 border-t border-zinc-200 dark:border-zinc-800 flex justify-end gap-2">
          <button type="button" onClick={onClose} className="px-3 py-1.5 text-sm">
            Cancel
          </button>
          <button
            type="button"
            onClick={() => onSave(body, title)}
            disabled={busy || body.trim().length === 0 || title.trim().length === 0}
            className="px-3 py-1.5 text-sm bg-emerald-500 text-white rounded-md font-medium disabled:opacity-50"
          >
            {busy ? "Rebuilding…" : "Save & rebuild PDF"}
          </button>
        </div>
      </div>
    </div>
  );
}

function SendDialog({
  template,
  roles,
  onClose,
  onSent,
}: {
  template: Template;
  roles: Role[];
  onClose: () => void;
  onSent: (submissionId: string) => void;
}) {
  const [submitters, setSubmitters] = useState(
    roles.map((r) => ({ role: r.name, email: "", name: "" })),
  );
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function send() {
    // Validate emails before sending so the user gets a clear, located error
    // instead of a generic server rejection.
    const bad = submitters.filter((s) => !EMAIL_RE.test(s.email.trim()));
    if (bad.length > 0) {
      setError(
        `Enter a valid email address for: ${bad.map((s) => s.role).join(", ")}.`,
      );
      return;
    }
    setBusy(true);
    setError(null);
    try {
      const res = await fetch("/api/submissions", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          templateId: template.id,
          submitters: submitters.map((s) => ({ ...s, email: s.email.trim() })),
        }),
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body?.error ?? `HTTP ${res.status}`);
      }
      const { submission } = (await res.json()) as { submission: { id: string } };
      onSent(submission.id);
    } catch (err) {
      setError(err instanceof Error ? err.message : "send_failed");
      setBusy(false);
    }
  }

  return (
    <div className="fixed inset-0 bg-black/40 flex items-center justify-center p-4 z-50">
      <div className="bg-white dark:bg-zinc-900 rounded-lg shadow-xl max-w-lg w-full p-6 space-y-4">
        <h2 className="text-lg font-semibold">Send for signing</h2>
        <p className="text-xs text-zinc-500">One row per signer role on the document.</p>
        <div className="space-y-3">
          {submitters.map((s, i) => {
            const c = colorForRole(s.role);
            const emailInvalid = s.email.length > 0 && !EMAIL_RE.test(s.email.trim());
            return (
              <div key={i} className="grid grid-cols-3 gap-2">
                <div
                  className="col-span-1 px-2 py-1 text-sm rounded-md flex items-center gap-2 truncate"
                  style={{ backgroundColor: c.fill, color: c.text }}
                >
                  <span
                    className="h-2 w-2 rounded-full shrink-0"
                    style={{ backgroundColor: c.border }}
                  />
                  <span className="truncate">{s.role}</span>
                </div>
                <input
                  type="text"
                  placeholder="Name"
                  value={s.name}
                  onChange={(e) =>
                    setSubmitters((prev) =>
                      prev.map((x, j) => (i === j ? { ...x, name: e.target.value } : x)),
                    )
                  }
                  className="col-span-1 px-2 py-1 text-sm rounded-md border border-zinc-300 dark:border-zinc-700 bg-white dark:bg-zinc-900"
                />
                <input
                  type="email"
                  required
                  placeholder="Email"
                  aria-invalid={emailInvalid}
                  value={s.email}
                  onChange={(e) =>
                    setSubmitters((prev) =>
                      prev.map((x, j) => (i === j ? { ...x, email: e.target.value } : x)),
                    )
                  }
                  className={`col-span-1 px-2 py-1 text-sm rounded-md border bg-white dark:bg-zinc-900 ${
                    emailInvalid
                      ? "border-red-400 focus:border-red-500 dark:border-red-700"
                      : "border-zinc-300 dark:border-zinc-700"
                  }`}
                />
              </div>
            );
          })}
        </div>
        {error && <p className="text-sm text-red-500">{error}</p>}
        <div className="flex justify-end gap-2">
          <button type="button" onClick={onClose} className="px-3 py-1.5 text-sm">
            Cancel
          </button>
          <button
            type="button"
            onClick={send}
            disabled={busy || submitters.some((s) => !s.email)}
            className="px-3 py-1.5 text-sm bg-emerald-500 text-white rounded-md disabled:opacity-50"
          >
            {busy ? "Sending…" : "Send"}
          </button>
        </div>
      </div>
    </div>
  );
}
