import { z } from "zod";

/**
 * Field on a document. Coordinates are normalized [0, 1] with top-left origin.
 * The single source of truth for field geometry — pdf-lib and signature stamping
 * convert at the boundary, never persist non-normalized coords.
 */
export const FieldType = z.enum([
  "text",
  "signature",
  "initials",
  "date",
  "checkbox",
  "number",
  "email",
  "phone",
  "image",
  "attachment",
]);
export type FieldType = z.infer<typeof FieldType>;

export const FieldSchema = z.object({
  id: z.string().uuid(),
  type: FieldType,
  pageIndex: z.number().int().min(0),
  x: z.number().min(0).max(1),
  y: z.number().min(0).max(1),
  w: z.number().min(0).max(1),
  h: z.number().min(0).max(1),
  required: z.boolean().default(false),
  submitterRole: z.string().min(1),
  label: z.string().optional(),
  defaultValue: z.string().optional(),
});
export type Field = z.infer<typeof FieldSchema>;

export const SubmitterRoleSchema = z.object({
  name: z.string().min(1),
  order: z.number().int().min(0).default(0),
});
export type SubmitterRole = z.infer<typeof SubmitterRoleSchema>;

export const TemplateDocumentSchema = z.object({
  attachmentId: z.string().uuid(),
  filename: z.string(),
  pageCount: z.number().int().min(1),
  /** Source markdown when the document was generated by AI. Used by the
   * builder's "Edit document" mode to re-render the PDF after edits. */
  bodyMarkdown: z.string().optional(),
});
export type TemplateDocument = z.infer<typeof TemplateDocumentSchema>;

export * from "./frontier-models";
